export type MonitorVaults = {
  name: string;
  pendingDepositsRatio: number;
  vaultStrength: number;
  baseTokenValue: number;
  address: string;
  tvl: number;
  scarceTokenValue: number;
  displayName: string;
  pendingDeposits: number;
  memberTokenRatio: number;
  sevenDaysChange: number;
  scarceTokenMarketCap: number;
  vaultIRR: number;
  vaultIrrAllTx: number;
  isHodlVault: boolean;
  needRebalanceFrom: string;
  lastRebalance: string;
  poolAddress: string;
  isInverted: boolean;
  wallPrice: number;
  scarceTokenPriceFromVault: number;
  targetVaultStrength: number;
};
