trigger: none

pr:
  branches:
    include:
      - '*' 
  paths:
    include:
      - src/*
      - deployment/*

variables:
- group: ichi-org-deployment-dev
  
pool:
  vmImage: "ubuntu-latest"

steps:
  - template: site-deployment-template.yml
    parameters:
      appSyncUrl: $(appSyncUrl)
      appSyncApiKey: $(appSyncApiKey)
      storageAccountName: $(storageAccountName)
      storageAccountKey: $(storageAccountKey)
