trigger: none

pr:
  branches:
    include:
      - '*' 
  paths:
    include:
      - src/*
      - deployment/*

variables:
  APP_SYNC_URL: $(appSyncUrl)
  APP_SYNC_API_KEY: $(appSyncApiKey)
  
pool:
  vmImage: "ubuntu-latest"

steps:
  - template: site-deployment-template.yml
    parameters:
      appSyncUrl: $(appSyncUrl)
      appSyncApiKey: $(appSyncApiKey)
      storageAccountName: $(storageAccountName)
      storageAccountKey: $(storageAccountKey)
