name: ichi.org (prod)

# on: workflow_dispatch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: http://ichiorg.stage.${{ github.actor }}.s3-website-us-east-1.amazonaws.com

    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: |
        npm i --force

    - name: Unit Tests
      run: |
        npm run test

    - name: Build website
      run: |
        echo "NODE_ENV: $NODE_ENV"
        touch .env.production
        echo GATSBY_APP_SYNC_URL=${{ secrets.APP_SYNC_URL_PROD }} >> .env.production
        echo GATSBY_APP_SYNC_API_KEY=${{ secrets.APP_SYNC_API_KEY_PROD }} >> .env.production
        cat .env.production
        npm run build
      env:
        GATSBY_APP_SYNC_URL: ${{ secrets.APP_SYNC_URL_PROD }}
        GATSBY_APP_SYNC_API_KEY: ${{ secrets.APP_SYNC_API_KEY_PROD }}

    - name: Deploy to Azure
      uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: 'public'
        connection-string: ${{ secrets.TMP_CONN_STRING }}

    # - task: AzureCLI@2
    #   displayName: Deploy site to Storage
    #   inputs:
    #     azureSubscription: devrg
    #     scriptType: pscore
    #     scriptLocation: inlineScript
    #     inlineScript: |
    #       az storage blob upload-batch -d '$web' -s $env:BUILD_DIR
    #   env:
    #     BUILD_DIR: $(Build.SourcesDirectory)/build/public
    #     AZURE_STORAGE_ACCOUNT: $(storageAccountName)
    #     AZURE_STORAGE_KEY: $(storageAccountKey)

    # https://github.com/Azure/cli
    # - name: Azure CLI script
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.34.1
    #     inlineScript: |
    #       az storage blob upload-batch -d '$web' --connection-string ${{ secrets.TMP_CONN_STRING }} -s $env:BUILD_DIR
