name: aquabera.com (stage)

on:
  push:
    branches:
      - master

jobs:
  stage:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and deploy stage
    runs-on: ubuntu-latest
    environment:
      name: stage

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Await CF Staging build
      id: cloudfare
      uses: WalshyDev/cf-pages-await@v1
      with:
        accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
        apiKey: ${{ secrets.CF_API_KEY  }}
        accountId: ${{ secrets.CF_ACCOUNT_KEY  }}
        project: 'aquabera'
        # Add this if you want GitHub Deployments (see below)
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        # Add this if you want to wait for a deployment triggered by a specfied commit
        # Commenting out to test if it works without this
        commitHash: ${{ steps.push-changes.outputs.commit-hash }}

    - name: Cloudfare URL
      run: |
        echo ${{ steps.cloudfare.outputs.url }}

  prod:
    needs: stage
    name: Build and deploy prod
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://aquabera.com

    steps:

    - name: Merge master -> production
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: master
        target_branch: production
        github_token: ${{ github.token }}

    - name: Await CF Staging build
      id: cloudfare
      uses: WalshyDev/cf-pages-await@v1
      with:
        accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
        apiKey: ${{ secrets.CF_API_KEY  }}
        accountId: ${{ secrets.CF_ACCOUNT_KEY  }}
        project: 'aquabera'
        # Add this if you want GitHub Deployments (see below)
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        # Add this if you want to wait for a deployment triggered by a specfied commit
        # Commenting out to test if it works without this
        commitHash: ${{ steps.push-changes.outputs.commit-hash }}
